USE instagram;

SELECT * FROM USER;
SELECT * FROM POST;

SET SQL_SAFE_UPDATES=0;-- IN SQL IT DOESNT ALLOW UPDATES DIRECTLY FOR SAFETY YOU HAVE TO SET THE SAFE UPDATES TO 0 WHICH IS 1 BY DEFAULT TO UPDATE  